### ISSUE TITLE
December 2018 meeting

### ISSUE THREAD

**Issue by ChristinaLK** [hpc-carpentry/coordination#1]
December 20, 2018; 5pm GMT / 12pm EST / 9am PST

**Agenda**

- Summaries of recent HPC Carpentry workshops
- update on current status of lessons, priorities
- questions from attendees (either live or from comments below)
- pathways for people to get involved
- planning for future calls

If you have questions / topics to discuss or are interested in getting involved in HPC Carpentry in a particular way, please comment below.  Thanks!

**Comment by aturner-epcc** [comment]
Can we add:

- Summaries of recent HPC Carpentry workshops

**Comment by razoumov** [comment]
Where do we meet?

**Comment by ChristinaLK** [comment]
@razoumov there was a zoom link in the email I sent out -- my original email went to the wrong list, so hopefully you have it now.

**Comment by razoumov** [comment]
@ChristinaLK Sorry, I cannot find any email (checked Spam), other than the GitHub notifications from this issue.

**Comment by ChristinaLK** [comment]
Are you on this list: https://carpentries.topicbox.com/groups/discuss-hpc?

**Comment by razoumov** [comment]
@ChristinaLK I believe I was ... still no email. Well, I have the link -- thanks.

**Comment by callaghanmt** [comment]
Thanks Christina! I'll plan to be there.
+1 to @aturner-epcc suggestion of a bit of feedback from past workshops

**Comment by hainest** [comment]
>pathways for people to get involved

Could we also include a bit of how to get _other_ folks involved? For example, how do we advertise our HPC workshops to non-XSEDE users who would still benefit from them?

**Comment by aturner-epcc** [comment]
I have come down with some sort of lurgy so will not be able to make the call - probably best for you all as I would have just coughed the whole time anyway! I had a few things I wanted to update on:

- I have taken the current hpc-shell and hpc-intro lessons and using the approach that Peter used in his hpc-in-a-day modified them so that they can be configured for different systems using parameters in the _config.yml files. The current built lessons remain mostly unchanged (some minor wording changes) as the default is to build for Graham at Compute Canada but there is also an example for Cirrus at EPCC to show people what a different system looks like. This should make it easier for people to use the lessons on different systems.
   + I have created and submitted a PR for hpc-shell with these changes and Peter has reviewed and left some useful comments. I will address these first thing in the new year and create the equivalent PR for hpc-intro.
- When I ran the workshops recently, I created an additional episode for the end of hpc-intro called 'Bootstrapping your use of HPC' (https://archer-cse.github.io/2018-12-06-turing-hpcintro/18-nextsteps/index.html) which had three different optional activities (listed below). I am not sure if we want this is the standard lesson or not and would be keen on people's thoughts. For example, would it be useful to have a library of domain-specific examples for such an episode?
   + Discuss with an expert (possibly also a group) what your next steps in using HPC will be - what do you not have that would allow you to proceed?
   + Exercise on taskfarming using a serial bioinformatics application and GNU parallel
   + Exercise on benchmarking a standard HPC application (GROMACS)
- We ran HPC Carpentry (shell + intro) at The Alan Turing Institute in London recently and got pretty good feedback. The only negative points we heard from attendees was that the hpc-shell part could have been done more quickly but there were other people who said that they really valued the time taken here to get them up and running with shell. My take is that this is the problem we always see when we have a range of experience on courses. We forgot to explicitly pair experienced people with less experienced ones at the start and if we had done this I think it could have helped.
   + We also plan to run a virtual tutorial in the new year for attendees on this course to help with any issues/questions that may have arisen since the workshop (they have access to the HPC system until mid-January as part of the course).
- Next HPC Carpentry workshop does not have a firm date yet but am aiming for Mar/Apr 2019.
- The UK Software Sustainability Institute is organising a CarpentryConnect event on 25-27 June 2019 in Manchester, in collaboration with Manchester’s Cathie Marsh Institute for Social Research and with support from Manchester’s Data Science Institute. You can sign up for further updates at: http://bit.ly/2SCbwBl . I have signed up for updates and it would be great to run some HPC Carpentry sessions there.

Apologies for not making it and I hope you all have a great Christmas and Hogmanay and look forward to speaking to you at the next meeting in Jan 2019.

BTW, @hainest I did not advertise our workshops to XSEDE at all! Granted, it was probably a bit too far for most of them to come for a 2 day workshop!! ;-)

**Comment by ChristinaLK** [comment]
@hainest I'm assuming that the primary audience for these calls is exactly the group of people who do NOT need XSEDE resources unless they don't have a local option.  So yes, we can discuss.
